### ISSUE TITLE
Bro is just NOT spawning bruh 

### ISSUE THREAD

**Issue by Tickle-Thompson** [nomnomab/lc-rolling-giant#1]
I have spent the past 1 in a half days trying to get the giant to spawn in general.

Me and my friend had tested out a collection of new mods I put on it, including Advanced Company, Expanded Company, and the Variety mod. Expanded company added a Christmas village map. We went in and the mansion map was loaded, with the rolling giant a room away, we scanned him and everything. Then we left. Unfortunately, that has been the last time I've seen him so far. 

At first, I was trying to get him to spawn in on offense with 100/100 chances to spawn, and he wouldn't. Later, I ran out of patience and went into the config settings and set him to spawn outside only, still wouldn't spawn. The only time I could've SWORN that it could have been him is when I had seen a mere silhouette outside, _once_. I spent entire in game days waiting for bro to spawn in even once so I could see my new configuration of him that I thought would make him more threatening to us. I even installed the enemy scanner mod to see if he was even spawning at all, I didn't see him, though I assumed the scanner still thought he was a coilhead.

That's when I figured the mod was bugged.

I then uninstalled The Variety mod (Didn't work). 

I then uninstalled The Expanded company mod (Didn't work).

I then uninstalled The Advanced Company mod (Didn't work).

I finally made a whole new mod profile with just him and set him to spawn with a 100% chance to spawn outside on Experimentation. I waited nearly a whole ingame day, on a fresh save/run. Buddy did not spawn.

I'm not sure if my main save is having compatibility issues, if it's with the mod itself, or if it's on my end

Im leaving a link to my default mod profile incase you or somone else wants to identify the problem themselves for whatever reason.

As of now, I am done tryna get dawg to spawn In and now ima just play with different mods or something. Happy new year.

**Comment by nomnomab** [comment]
Hello there, sorry you haven't been able to find the giant.

Firstly, the spawn rate isn't a percentage, it's a weight, as all enemies have a weight that gets chosen from over time. Higher numbers just means a higher chance of getting picked, but not guaranteed. You can also go past 100 (which is the game's default) if you wanted to, albeit I didn't document that. I'll be making a patch detailing that in the config soon. For reference, it uses the same weights as the Coil Head.

Secondly, I don't see a mod profile link in your message. I also don't see a version number that you tested on, nor your config being used. More information will be useful to work with, so if can provide that, that would be great.

Thanks.

**Comment by nomnomab** [comment]
I just tested with v2.1.0 four times on Experimentation with a weight of 6, and got no giants, which makes sense as other monsters have higher weights so it lost in the picks. Which is very vanilla in that aspect.

I also tested once on March, which has a weight of 10 by default and got one on my first visit, which is a very low chance. So the mod is definitely functional.

**Comment by nomnomab** [comment]
Also turns out that a soft dependency to another mod, that was guarded from breaking the mod loading, managed to break the mod loading if you didn't have LethalSettings...

I'll be pushing a hotfix asap, if this ends up being your issue, I apologize 🫡. The fix will also have a probability curve, higher default chances, and some extra descriptions for what the numbers can do.
