### ISSUE TITLE
Disable at night setting bug

### ISSUE THREAD

**Issue by Xiernix** [nomnomab/lc-rolling-giant#11]
The rolling giant turns pink and transparent and continues to play it's rolling sound effect if it was moving when it shuts off for the night.
![Screenshot_1](https://github.com/nomnomab/lc-rolling-giant/assets/158011451/cf61c570-e805-4f4c-a248-99359752cebd)

**Comment by nomnomab** [comment]
Seems the material got excluded from the asset bundle somehow 👍 Will look into the sounds as well.
