### ISSUE TITLE
[Minor] Spawn weight fluctuating 

### ISSUE THREAD

**Issue by Xiernix** [nomnomab/lc-rolling-giant#12]
The rolling giants spawn weight seems to go up or down in the console logs every time something is spawned. It also seems to be adding more onto whatever the weight is set to in the config. (e.g. 45 becomes 57. I was testing with a weight of 1000 and it started at 1111) Not sure if this is intentional or not but thought it was odd that it wasn't consistent with the config settings.
![Screenshot_1](https://github.com/nomnomab/lc-rolling-giant/assets/158011451/2de1a69a-9afa-4f24-827c-89eb1d57dadb)
![Screenshot_2](https://github.com/nomnomab/lc-rolling-giant/assets/158011451/82007356-1cae-4c21-b4f3-78544d6c2a80)
![Screenshot_3](https://github.com/nomnomab/lc-rolling-giant/assets/158011451/b5bc1ecb-e095-4c35-b79a-89202c9454d9)

**Log**
[LogOutput.log](https://github.com/nomnomab/lc-rolling-giant/files/14320681/LogOutput.log)

**Comment by nomnomab** [comment]
Hello 👋

I don't do anything with spawning outside of the initial config options. Vanilla spawns fluctuate over time, so that looks normal to me. In that case, the game basically lowers the chance so other things have a chance to spawn.
