### ISSUE TITLE
Sound doesn't trigger

### ISSUE THREAD

**Issue by RegisRobert** [nomnomab/lc-rolling-giant#2]
Hello,
We are using the last version of the mod,
It has been installed with r2modman however when facing the giant (which is terrifying gg ) no sound comes up from his mouth.
Maybe he doesn't really make any noise, maybe it's a bug, I just wanted to report it to you.

Nice mod by the way very scary !

**Comment by nomnomab** [comment]
Thanks for sharing this! I fixed the audio issue and the update will be pushed in a little bit.
