### ISSUE TITLE
(feature request) all moons spawn weight

### ISSUE THREAD

**Issue by HamedAlmanthari** [nomnomab/lc-rolling-giant#3]
hello. it would be appreciated if you could add an option in the config that would allow the rolling giant to spawn in all moons (including modded moons). from what i understand, the rolling giant now only spawn in vanilla moons by default. so you have to add each modded moon in the config file. however, i don't know the name of each moon. so it would be much appreciated if you could add in the config an option to allow it to spawn in every moon and also a general spawn weight for every moon.

**Comment by nomnomab** [comment]
Hello! Thanks for the suggestion, I added it into the mod and will be pushing an update in a few minutes.

**Comment by HamedAlmanthari** [comment]
ty so much
