### ISSUE TITLE
Is it possible to make a guide for how to build this locally?

### ISSUE THREAD

**Issue by Edwinsiddy1** [nomnomab/lc-rolling-giant#4]
I would love to mess with this mod, but have no idea how you set up the project to build properly. any tips would be greatly appreciated!

**Comment by nomnomab** [comment]
Sure! Just pushed a csproj slight change, but all you should have to do is:

### Removing the local plugin package step

Remove the `PreBuild` step in the csproj, and replace the `PostBuild` step with

```cs
<Target Name="PostBuild" AfterTargets="PostBuildEvent">
  <Exec Command="cd $(NetcodePatcherDir)&#xA;NetcodePatcher.dll $(TargetDir) deps/&#xA;xcopy /y /d &quot;$(TargetDir)$(TargetName).dll&quot; &quot;$(GameDir)\BepInEx\plugins\RollingGiant\&quot;&#xA;" />
</Target>
```

Also remove:

```cs
<ItemGroup>
  <Folder Include="plugin\BepInEx\plugins\RollingGiant\" />
</ItemGroup>
```

### Initial steps

1. Open the .csproj
2. Change `<GameDir>` to where your game is installed
3. Change `<NetcodePatcherDir>` to where you have the [Unity Netcode Patcher](https://github.com/EvaisaDev/UnityNetcodePatcher) extracted

> Can also remove the enter netcode patcher step if you want to use the nuget version instead, but I haven't updated to that yet, so I haven't looked into it

4. Build

When built, it will patch the dll and then copy the dll to the game's plugin folder.

If you don't want the auto-copying to the game directory, then remove this from the `PostBuild` step:

```cs
xcopy /y /d &quot;$(TargetDir)$(TargetName).dll&quot; &quot;$(GameDir)\BepInEx\plugins\RollingGiant\&quot;&#xA;
```

Let me know if this makes sense!

**Comment by Edwinsiddy1** [comment]
These steps (along with a dotnet restore) allowed me to successfully build it! However, when running the game, the game breaks I see this in the console:

`[Error  : Unity Log] Unable to open archive file: H:/SteamLibrary/steamapps/common/Lethal Company/BepInEx/plugins/rollinggiant`
`[Error  : Unity Log] Failed to read data for the AssetBundle 'H:\SteamLibrary\steamapps\common\Lethal Company\BepInEx\plugins\rollinggiant'.`
`[Error  :Rolling Giant] Failed to load asset bundle! System.NullReferenceException: Object reference not set to an instance of an object
  at RollingGiant.Plugin.LoadAssets () [0x00036] in <9c2d69421e3547d9815b2763eaf3fe6d>:IL_0036`
`[Error  :Rolling Giant] Failed to load assets! System.NullReferenceException: Object reference not set to an instance of an object
  at RollingGiant.Plugin.LoadAssets () [0x00117] in <9c2d69421e3547d9815b2763eaf3fe6d>:IL_0117`
  
  Is there something I'm missing with loading the assets? I did notice that they weren't anywhere I could find in the files.

**Comment by nomnomab** [comment]
Seems like you don't have the assetbundle next to the plugin DLL. Can you check to make sure that it is there?

**Comment by Edwinsiddy1** [comment]
Is there a way to generate/extract it from this file, or should I just take it from the uploaded project on thunderstore? I tried taking it from thunderstore (as well as applying my built dll to the thunderstore version) but my character was unable to move/look around once I loaded in, which I assume means the game is completely broken.

**Comment by nomnomab** [comment]
You can take the assetbundle from thunderstore and put it next to the dll in the game's plugin folder. 

If you kept the copy in the post-build event, then it puts the dll in the `$(GameDir)\BepInEx\plugins\RollingGiant\` directory, so put the assetbundle in there too. 

If you are copying the dll manually, you just need the assetbundle next to it. This project doesn't build one since it's built in Unity into the game's plugin folder above, which is later used in my original build step to copy into the local package folder for Thunderstore.


https://github.com/nomnomab/lc-rolling-giant/assets/28305689/dd3b59c5-5fc3-4c61-a506-1d91394a26d9

**Comment by Edwinsiddy1** [comment]
Yeah, that's what I did, but for some reason the game is completely broken once I load in, with no errors shown. I did notice my dll is 79kb compared to your 77kb, not sure what that is about, maybe the fact that I'm using the most recent netcodepatcher? I couldn't get 2.4.0 to run properly

heres the dll I'm making
[RollingGiant.zip](https://github.com/nomnomab/lc-rolling-giant/files/14014717/RollingGiant.zip)

**Comment by nomnomab** [comment]
Looking at the DLL you sent it doesn't look like it was patched. That's most likely the issue. I only use 2.4.0, but I think that has issues with Visual Studio (if you are using that).

**Comment by Edwinsiddy1** [comment]
All right, I'll look into getting 2.4.0 running, thanks!

**Comment by Edwinsiddy1** [comment]
Seems that fixed it! oddly enough the dll is now 84kb somehow, but it works! Thanks!

**Comment by Kradre** [comment]
@nomnomab Hello again! Kind of have some issue still with NetworkPatcher 2.4.0
Can't figure out the error:
`Initializing NetcodePatcher 2.4.0
Added (RollingGiant.dll) to patch list.
Patching : RollingGiant.dll
[Warning]: Failed to patch (RollingGiant.dll): System.NullReferenceException: Object reference not set to an instance of an object.
   at NetcodePatcher.CodeGen.ILPostProcessorFromFile.ILPostProcessFile(String assemblyPath, String[] references, Action`1 OnWarning, Action`1 OnError) in O:\github\UnityNetcodeWeaver\NetcodePatcher\CodeGen\ILPostProcessorFromFile.cs:line 151
   at NetcodePatcher.Patcher.Patch(String pluginPath, String managedPath) in O:\github\UnityNetcodeWeaver\NetcodePatcher\Main.cs:line 230
`
