### ISSUE TITLE
One more thing, would it be possible to share the unity asset project used to make the assetbundle?

### ISSUE THREAD

**Issue by Edwinsiddy1** [nomnomab/lc-rolling-giant#5]
I'm having fun tweaking with the code, but would like to also look into changing somethings with the assetbundle, but its been messy trying to reverse-engineer the assetbundle. If you aren't comfortable with this request its all good.

**Comment by nomnomab** [comment]
Sorry, just now saw this. 

I will send you a partial file list, it won't include the game scripts or the game's scriptable objects, and some stuff may not link properly. You'll still need to do the normal set-up of asset ripping, guid-patching, and using the LC template for anything that is missing (or use my [latest patching tool](https://github.com/nomnomab/lc-project-patcher)).

I just ask that you do not re-distribute the unity files I'm giving 👍

[RollingGiant_PartialFiles.zip](https://github.com/nomnomab/lc-rolling-giant/files/14072857/RollingGiant_PartialFiles.zip)
