### ISSUE TITLE
RandomlyMoveWhenLooking AI

### ISSUE THREAD

**Issue by Danrejk** [nomnomab/lc-rolling-giant#6]
The Rolling Giant always moves when not looking at it and only stops when you look at it, continuing to move randomly.
To my understanding it should work like the Inverse Coilhead, but instead of constantly moving while you look at it, it would move randomly.

**Comment by nomnomab** [comment]
`RandomlyMoveWhenLooking` moves when not looking at it, and randomly when looking at it. It's basically a Coilhead, but doesn't always stay still when staring at it.

So what you described sounds correct, unless I'm missing something? If it isn't doing that, then I'll need to see a video + your config. 👍

**Comment by Danrejk** [comment]
I simply misunderstood how it worked. Thanks for the explanation
