### ISSUE TITLE
Suggestion for Scarier and more Unpredictable AI Behavior

### ISSUE THREAD

**Issue by Triangleman1** [nomnomab/lc-rolling-giant#9]
Rather than changing the AI type each moon, having the AI type randomly switch throughout the course of the day would be far more unpredictable and better match up with the the giant's behavior in The Oldest View. In the series, it first acted like a coilhead, then dropped the facade and became far more aggressive. A lot of the horror came from these shifting behaviors. Having an option for it to switch AI types every minute or so would somewhat replicate this, and in my opinion make it significantly scarier, as players would never be able to fully predict its next move. What pacifies it one minute might anger it the next, and vice versa.

**Comment by nomnomab** [comment]
This is a good idea! 

I may shift it to change after an in-game hour, or X amount of in-game hours to stay in line with what the game normally does, but I shall try it out 👍

**Comment by nomnomab** [comment]
Added 👍
